apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-build
spec:
  inputs:
    resources:
      - name: git
        type: git
  outputs:
    resources:
      - name: image
        type: image
  steps:
      # The name of the step
    - name: pytest
      image: python
      command:
        - /bin/bash
        - -c
      args:
        # Changes to the app/ directory, installs required dependencies, and run all
        # the tests with pytest
        - cd /home/klewandowski/tekton-demo/app && pip3 install -r requirements.txt && pip3 install -r dev_requirements.txt && pytest .
    - name: kaniko
      image: gcr.io/kaniko-project/executor
      env:
        - name: "DOCKER_CONFIG"
        value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/home/klewandowski/tekton-demo/Dockerfile
        - --destination=${outputs.resources.image.url}
        - --context=/home/klewandowski/tekton-demo