apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-test-deploy-app
spec:
  resources:
    - name: git
      type: git
    - name: image
      type: image
  tasks:
    - name: build-test-app
      taskRef:
        name: build-test-app
      resources:
        inputs:
          - name: git
            resource: git
        outputs:
          - name: image
            resource: image
    - name: deploy-app
      taskRef:
        name: deploy-app
      resources:
        inputs:
          - name: image
            resource: image