apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-test-deploy-app-run
spec:
  pipelineRef:
    name: build-test-deploy-app
  resources:
    - name: git
      resourceRef:
        name: example-git
    - name: image
      resourceRef:
        name: example-image