apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-test-deploy-app-pipeline-run-
spec:
  pipelineRef:
    name: build-test-deploy-app-pipeline
  resources:
    - name: git
      resourceRef:
        name: example-git
    - name: image
      resourceRef:
        name: example-image